pipeline{
    agent any

    environment {
        IMAGE_NAME = "renatoapaza/python-app"
        DOCKERHUB_CREDS = credentials("dockerhub")
        NameContainer = "python-app"
    }

    stages{
        stage('Build image') {
            steps {
                sh 'terraform init'
                sh 'docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} ./python-app'
            }
        }
        
        /*
        stage('Run Unit Test') {
            steps {
                sh 'cd python-app && pip install -r requirements.txt && python3 -m unittest test_app.py'
            }
        }
        */

        stage("Docker push"){
            steps{
                //sh 'echo ${DOCKERHUB_CREDS_PSW}'
                //sh 'echo ${DOCKERHUB_CREDS_PSW} | docker login -u ${DOCKERHUB_CREDS_USR} --password-stdin'
                sh 'docker login -u ${DOCKERHUB_CREDS} --password-stdin'
                sh 'docker push ${IMAGE_NAME}:${BUILD_NUMBER}'
            }
        }

/*
        stage("Docker run"){
            steps{
                input message: 'Continue?'
                sh """
                if docker ps -a | grep -q ${env.NameContainer}; then 
                    docker stop ${env.NameContainer} && docker rm ${env.NameContainer}
                fi
                docker run -d --name ${env.NameContainer} -p 5000:5000 ${IMAGE_NAME}:${BUILD_NUMBER}
                """
            }
        }
        */
        
    }
    
    post {
        always {
            sh 'docker logout'
        }
    } 
}