apiVersion: apps/v1
kind: Deployment
metadata:
 name: python-app
 namespace: python-app
 labels:
  app: python-app
spec:
 replicas: 1
 selector:
  matchLabels:
    app: python-app
 template:
  metadata:
    labels:
      app: python-app
  spec:
    imagePullSecrets:
    - name: python-app
    containers:
    - name: python-app
      image: renatoapaza/python-app:latest 
      ports:
      - containerPort: 5000
      volumeMounts:
      - mountPath: "/tmp"
        name: mypd
    volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: python-app-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: python-app-pvc
 namespace: python-app
spec:
 storageClassName: standard
 accessModes:
 - ReadWriteOnce
 resources:
  requests:
    storage: 50Mi

---

apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: python-app
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007